### PR TITLE
Feature/ttl index

### PR DESCRIPTION
**Pull request by hkernbach**

### CODE REVIEW

**Comment by hkernbach** [comment]
http://jenkins.arangodb.biz:8080/view/Java/job/arangodb-java-driver-pr/214/

**Comment by hkernbach** [comment]
http://jenkins01:8080/job/arangodb-ANY-java-driver-matrix-new/23/ARANGO_EDITION=enterprise,ARANGO_MODE=singleserver,ARANGO_STORAGE_ENGINE=rocksdb,DRIVER_HOSTS_ACQUIRE=true,SERVER_NODE=java/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/Java/job/arangodb-ANY-java-driver-matrix/214/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/Java/job/arangodb-java-driver-pr/218/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/Java/job/arangodb-java-driver-pr/220/

**Comment by hkernbach** [comment]
http://jenkins01:8080/view/Java/job/arangodb-java-driver-pr/223/

**Comment by rashtao** [comment]
http://jenkins01:8080/view/Java/job/arangodb-java-driver-pr/224/

**Pull request merged**
