### PR TITLE
remove close host

### PR DESCRIPTION
**Pull request by zz123happy**

### CODE REVIEW

**Comment by rashtao** [comment]
Hi @zz123happy 

Many thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository - even for such small changes.

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Comment by rashtao** [comment]
fixes https://github.com/arangodb/arangodb-java-driver/issues/346

**Comment by zz123happy** [comment]
HI @rashtao 

I have sign  the Apache 2 CLA for ArangoDB and send a scanned copy to cla@arangodb.com as required, waiting for your reply ~

Thank you.

**Comment by rashtao** [comment]
Hi @zz123happy , 
unfortunately we cannot find any signed CLA matching your GitHub username.
Can you please resend it and mark that is for the GitHub user `zz123happy`?

**Comment by zz123happy** [comment]
HI @rashtao

I have resigned the Apache 2 CLA for ArangoDB and resend a scanned copy to cla@arangodb.com as required, the username is zz123happy, waiting for your reply ~

Thank you.

**Pull request merged**
