### PR TITLE
Batch driver performance fix

### PR DESCRIPTION
**Pull request by jan-zajic**
I fix performance issue in batch driver. I try to run several thousand operations in one batch request, but there will never be send to server before my fix. It's because String concatenation within loop. After fix, i run very large batch queries without problem. 

Where you're concatenating in a loop - that's usually when the compiler can't substitute StringBuilder by itself.

### CODE REVIEW

**Comment by fceller** [comment]
@jan-zajic thanks a lot for your contribution. We are using the Apache 2 license for the source. You are also using a Apache CLA for contribution. Can you please sign, scan and email https://www.arangodb.com/documents/cla.pdf to hackers (at) arangodb.com 

Again thanks a lot

**Comment by dothebart** [comment]
@jan-zajic we really liked to accept your contribution. Is it possible for you to sign a CLA as @fceller questioned?

**Comment by jan-zajic** [comment]
I sent it to email hackers (at) arangodb.com and cla (at) arangodb.com with subject "PR #31".

**Comment by fceller** [comment]
@jan-zajic thanks a lot and thank you again for you contribution

**Pull request merged**
